import 'package:firebase_core/firebase_core.dart';

/// Temporary placeholder Firebase options for Kulters.
///
/// Replace this file by running:
///   flutterfire configure
/// and selecting your Firebase project. That will generate a new
/// `firebase_options.dart` with real values.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace with real options generated by FlutterFire.
    // These placeholder values let the app compile but will NOT connect
    // to a real Firebase project.
    return const FirebaseOptions(
      apiKey: 'AIzaSyAu_4BkquDPxHCq7dui7b7jIrRqEg585f0',
      appId: '1:409673259018:android:73be1f7043888064bfa7f3',
      messagingSenderId: '409673259018',
      projectId: 'kulters',
      storageBucket: 'kulters.firebasestorage.app',
    );
  }
}

